### ISSUE TITLE
Gathering incorrect number of licenses

### ISSUE THREAD

**Issue by vfm2** [github-copilot-resources/copilot-metrics-viewer-power-bi#4]
Hey Team, a team has configured this powerBI report for their enterprise, but are getting an incorrect license report of only 50 users with a license, when there are 239 users with licenses. Is there a setting that needs to be update to account all licenses? Is there a fix for this?

Query for reference.

![Image](https://github.com/user-attachments/assets/691928b1-a06d-458a-a625-dbc69fb0145a)

**Comment by vfm2** [comment]
Hi team, any update on this?

**Comment by jasonmoodie** [comment]
@vfm2 - Sorry for the delay. The API doesn't return seats, but reports on **total_active_users**. See below:
https://docs.github.com/en/rest/copilot/copilot-usage?apiVersion=2022-11-28#get-a-summary-of-copilot-usage-for-enterprise-members

I believe there's another API that has seats. I'll get back to you with that.

**Comment by jasonmoodie** [comment]
Hello @YashuC1487 / @vfm2 - To get seat assignments of GH Copilot you can use the API documented below. I would use the GH Copilot metrics API data source as an example and modify the API URL. Your PAT will already be scoped with correct permissions.

[https://docs.github.com/en/rest/copilot/copilot-user-management?apiVersion=2022-11-28](https://docs.github.com/en/rest/copilot/copilot-user-management?apiVersion=2022-11-28)

**Comment by vfm2** [comment]
Hi @jasonmoodie - thank you for your response! This issue has been resolved, but another issue has come up - the data for usage under URL https://api.github.com/enterprises/ENTERPRISE/copilot/usage is only capturing up to Nov 24. Can you validate? 

Let me know if you would prefer me to close this issue and create another. 

Thank you.
